apiVersion: apps/v1
kind: Deployment
metadata:
  name: fibonacci-bench-app
spec:
  selector:
    matchLabels:
      application-name: fibonacci-bench-app
  replicas: 3
  template:
    metadata:
      labels:
        application-name: fibonacci-bench-app
    spec:
      containers:
        - name: fibonacci-bench
          image: "abhi170599/fibonacci-bench"
          imagePullPolicy: Always
          ports:
            - name: app
              containerPort: 5005
