apiVersion: v1
kind: Service
metadata:
  name: fibonacci-bench-lb
  labels:
    application-name: fibonacci-bench-app
  annotations:
    service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "100"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5005
  selector:
    application-name: fibonacci-bench-app